### ISSUE TITLE
mine gets stuck

### ISSUE THREAD

**Issue by mrhammerthis** [DeviatorZ/league-account-checker#32]
For some reason mine gets stuck on "waiting for RiotClient ot update..."

**Comment by DeviatorZ** [comment]
does it happen while running multi-threaded? someone else had this issue before and it's caused by the system.yaml. Change from "KeystoneFoundationBetaWin" to "KeystoneFoundationLiveWin"
![image](https://github.com/DeviatorZ/league-account-checker/assets/123499556/6ccd7560-370d-4b55-ab7e-efc82bd7631a)
![image](https://github.com/DeviatorZ/league-account-checker/assets/123499556/8f0caba5-87a2-4e94-bcfa-937fc3a1a27c)

**Comment by mrhammerthis** [comment]
I'm not sure, but it did fix when I restarted my computer and made sure "Blitz.gg" wasn't running.

**Comment by DeviatorZ** [comment]
Change from "KeystoneFoundationBetaWin" to "KeystoneFoundationLiveWin". It should be Live, not Beta.

**Comment by mrhammerthis** [comment]
> Change from "KeystoneFoundationBetaWin" to "KeystoneFoundationLiveWin". It should be Live, not Beta.

I'm retarded and can't read lmao i'll try that now

**Comment by DeviatorZ** [comment]
Let me know if it fixes things for you. I'll add automatic modification of the config file if it does.

**Comment by mrhammerthis** [comment]
yep looks like it worked flawlessly, I wonder how i fixed it last time though.
